entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

api:
  dashboard: false
  insecure: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  tlsresolver:
    acme:
      tlschallenge: true
      email: 173137@stud.prz.edu.pl
      storage: /letsencrypt/acme.json